"""
1. Human Message - represents the input from a user.
2. System Message - The system message which is used to provide instructions or context to the model.

3. Function Message - the function message represents the tool of a function call.

4. AI message - The AI message which represents responses generated by AI models.

5. Tool Message - Tool message which is similar to the function message but specific to tool usage.
"""